accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

e_food/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "E-Food Admin"
admin.site.site_title = "E-Food"
admin.site.index_title = "E-Food Administration Panel"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUSerForm(UserCreationForm):
    email = forms.EmailField(required=True)
    phone_number = forms.CharField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "phone_number", "first_name", "last_name", "password1", "password2")

    def save(self,commit=True):
        user = super(NewUSerForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.phone_number = self.cleaned_data["phone_number"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        if commit:
            user.save()
        return user

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from .forms import NewUSerForm

def signup_view(request):
    if request.method == 'POST':
        form = NewUSerForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main:home')
    else:
        form = NewUSerForm()
    return render(request, 'accounts/signup.html', { 'form': form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('main:home')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

def logout_view(request):
    if request.method == 'POST':
            logout(request)
            return redirect('/')

accounts/templates/accounts/login.html
{% extends "main/layout.html" %}
{% load crispy_forms_tags %} 
{% block content %}
<div class="container">
    <h1>Login</h1>
    <div class="form-border">
        <form class="site-form" action="{% url 'accounts:login' %}" method="post">
            <div class="logging-form">
                {% csrf_token %}
                {{ form|crispy }}
                {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <input type="submit" value="Login" class="btn" />
            </div>
        </form>
    </div>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}"><u>Sign Up</u></a></p>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "main/layout.html" %}
{% load crispy_forms_tags %} 
{% block content %}
<div class="container">
    <h1>Signup</h1>
    <div class="form-border">
        <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Signup" class="btn">
        </form>
    </div>
</div>
{% endblock %}